
/* Auto-generated by md-to-tsx.mjs */
import { useEffect } from "react";
import { Link, useSearch } from "wouter";
import Header from "@/components/site/Header";
import Footer from "@/components/site/Footer";
import Section from "@/components/site/Section";
import { Button } from "@/components/ui/button";
import { ArrowLeft, Printer } from "lucide-react";
import { seoConfig } from "@/content/seo";

export default function AIForKindergartenGuide() {
  const search = useSearch();
  const isPrintMode = search === "?print=true";

  useEffect(() => {
    document.title = "AI til barnagarð: Nýtiligar amboð fyri dagliga arbeiði - " + seoConfig.title;

    const metaDescription = document.querySelector('meta[name="description"]');
    const content = "Praktisk vegleiðing um hvussu vitlíki kann hjálpa barnagarðslærarum við dagligu arbeiði, leskanarplaner og samskifti við foreldur.";
    if (metaDescription) {
      metaDescription.setAttribute('content', content);
    } else {
      const meta = document.createElement('meta');
      meta.name = 'description';
      meta.content = content;
      document.head.appendChild(meta);
    }

    // Auto-print if print mode
    if (isPrintMode) {
      window.print();
    }
  }, [isPrintMode]);

  const handlePrint = () => {
    window.print();
  };

  // Custom styles for this specific guide
  const customStyles = `
    @media print {
      .no-print { display: none !important; }
      .guide-content { 
        max-width: 100% !important;
        padding: 0 !important;
        font-size: 12pt !important;
      }
    }

    /* Custom theme colors for this guide */
    .guide-accent { color: #16a34a; }
    .guide-bg-accent { background-color: #f0fdf4; }
    .guide-border-accent { border-color: #16a34a; }
  `;

  return (
    <>
      <style dangerouslySetInnerHTML={{ __html: customStyles }} />

      {!isPrintMode && <Header />}

      {/* Print-only header - hidden on screen, shown in print */}
      <div className="print-header hidden">
        <div className="flex justify-between items-center">
          <span>AI til barnagarð</span>
          <span>Vitlíkisstovan</span>
        </div>
      </div>

      {/* Print-only footer - hidden on screen, shown in print */}
      <div className="print-footer hidden">
        <div className="flex justify-between items-center text-xs">
          <span>© 2024 Vitlíkisstovan</span>
          <span className="print-page-number"></span>
        </div>
      </div>

      <main className={`${!isPrintMode ? 'pt-16' : ''} bg-white`}>
        {/* Navigation - Hidden in print */}
        {!isPrintMode && (
          <div className="no-print border-b">
            <Section className="py-4">
              <div className="flex justify-between items-center max-w-4xl mx-auto">
                <Link href="/user-guides">
                  <Button variant="ghost" size="sm">
                    <ArrowLeft className="h-4 w-4 mr-2" />
                    Aftur til vegleiðingar
                  </Button>
                </Link>
                <Button variant="outline" size="sm" onClick={handlePrint}>
                  <Printer className="h-4 w-4 mr-2" />
                  Prenta / Goym sum PDF
                </Button>
              </div>
            </Section>
          </div>
        )}

        {/* Guide Content */}
        <Section className="py-8 sm:py-12">
          <article className="guide-content mx-auto max-w-4xl prose prose-gray prose-lg">
            <h1><strong>AI til barnagarð: Nýtiligar amboð fyri dagliga arbeiði</strong></h1>
            <p><strong>Praktisk vegleiðing um hvussu vitlíki kann hjálpa barnagarðslærarum við dagligu arbeiði, leskanarplaner og samskifti við foreldur.</strong></p>
            <hr />
            <p><strong>Fyri hvørn henda vegleiðing er</strong></p>
            <ul>
              <li><p><strong>Barnagarðslærarar</strong> og annað barnagarðsstarvsføllk.</p></li>
              <li><p>Fólk við <strong>lítla ella onki AI-royndir</strong>; telefon-fyrst, einføld uppseting.</p></li>
              <li><p><strong>Tíðarskuld</strong> og nógv ymisk arbeiðsuppgávur (t.d. leskanarplaner, samskifti við foreldur, skjalfesting).</p></li>
              <li><p>Leitar eftir <strong>skjótum úrslitum, sum tú kanst brúka í dag</strong> (bara chatbotar—ChatGPT, Copilot, Gemini).</p></li>
            </ul>
            <p><strong>Ikki fyri</strong></p>
            <ul>
              <li><p><strong>At skifta út tína dømikraft ella umsorgararbeiði.</strong> AI skrivar uppskot; <strong>tú</strong> tekur avgerðir.</p></li>
              <li><p><strong>Fakliga ráðgeving</strong> um barnarækt ella viðurskifti, sum krevja serfrøðikunnleika.</p></li>
              <li><p>Arbeiði, sum krevur <strong>persónlig ella viðkvæm dátur</strong> uttan samtykt og trygt kervi.</p></li>
              <li><p><strong>Sjálvvirkni ella integration.</strong> Henda vegleiðing er <strong>bert chat</strong> (avrita/líma).</p></li>
            </ul>
            <hr />
            <h2 id="ver-varin-við-person-upplysingar"><strong>Ver varin við persónupplýsingar</strong></h2>
            <p><strong>Einføld regla:</strong> um ein ókendur kann kenna aftur eitt barn, foreldrapart ella starvsføllk, <strong>legg ikki hetta í chattin</strong>.</p>
            <p><strong>Hugsa postkort, ikki lokin bræv.</strong> Almenn chat-amboð kunnu vera sum radiosamrøða: tá ið sagt, er tað burtur. Brúka bara <strong>almennar ella duldar</strong> innleiðingar, uttan tú ert <strong>100% viss</strong> um, at tú brúkar eitt arbeiðspláss-samtykt, tryggt kervi.</p>
            
            <h3 id="hvad-er-trygt-at-deila"><strong>Hvat er trygt at deila (grønt)</strong></h3>
            <ul>
              <li><p><strong>Almennar støður</strong> ("eitt barn var órólígt í dag").</p></li>
              <li><p><strong>Duldar fyrimyndareign</strong> ("Barn A", "Foreldur B", "Flokkur 1").</p></li>
              <li><p><strong>Samanlagdar smálutir</strong> (morgun/eftirmiddag, "umleið hádegi" í staðin fyri nákvæmar tíðir).</p></li>
              <li><p><strong>Ikki-kennandi samanhang</strong> (aldursgrupp, talið á børnum, tøk, veður).</p></li>
              <li><p><strong>Uppspuna/hugburðarlig dømi</strong> fyri venjing.</p></li>
            </ul>

            <h3 id="hvad-er-ikke-trygt"><strong>Hvat er ikki trygt (reytt)</strong></h3>
            <ul>
              <li><p><strong>Nøvn, upphavsbókstavir, føðingardagar, adressur</strong>, telefontal, teldupostar.</p></li>
              <li><p><strong>Myndir ella andlit</strong>, serstøk kennimerki, ID-tal, saksnummur.</p></li>
              <li><p><strong>Heilsuplikatir, allergiar</strong> knýtt til navngivin persón.</p></li>
              <li><p><strong>Nákvæm skema/tíðir</strong> sum peika á ávísan persón.</p></li>
              <li><p><strong>Hendingasmálutir</strong> sum gera ein persón kennanliga.</p></li>
            </ul>

            <h3 id="10-sekund-pii-check"><strong>10-sekund persónupplýsing check</strong></h3>
            <ul>
              <li><p><strong>Kann onkur uttanfyri liðið vita, hvør hetta er?</strong> Um ja → <strong>stans</strong>.</p></li>
              <li><p><strong>Hevur tín arbeiðspláss samtykt AI-uppseting fyri persónupplýsingar á skrivi?</strong> Um nei → <strong>dulda ella legg ikki inn</strong>.</p></li>
            </ul>

            <hr />
            <h2 id="hvussu-at-hugsa-um-ai-sum-partnar"><strong>Hvussu at hugsa um AI sum partnar</strong></h2>
            <p>Hugsa um AI sum tín skapandi, men eitt sindur óvantaða arbeiðsfella, sum kann taka ymisk luttøk - sum tín "Skapandi Samrøðufella", "Ætlanagerð Hjálpari" ella "Samskifti Hjálpari".</p>
            <p>AI kann síggja út sum ótrúliga smart, men tað fer altíð at lurka óvantaðar villur inn, so <strong>hald hendurnar fast á stýrið</strong>. Kanna altíð úrslitið frá AI nøgdi, serliga um tað fevnir um týdningarmikið samskifti ella skjalfesting.</p>
            <p>AI kennir ikki til tína nákvæmu støðu, uttan tú greiðligt segur tað til. Ver tann, sum skrivar: "Eg eri barnagarðslærari í Føroyum, arbeiði við 15 børnum í aldrinum 3-5 ár." Tey fleiri viðkomandi samanhangur tú gevur - talið á børnum, uppseting, tilfar, avmarkingar - tey betri uppskotini fáa tú.</p>

            <hr />
            <h2 id="skapandi-samrodufella-aktivitetar-og-planer"><strong>Skapandi samrøðufella (aktivitetar og planer)</strong></h2>
            <p>Sum barnagarðslærari eru tínir dagar fyllti við beinleiðis umsorgaruppgávur og skipandi aktivitetar. At finna nýggjar, hugfangnandi aktivitetar skjótt kann vera avbjóðandi, serliga við avmarkaðari tíð og tilfar. AI virkar sum tín skapandi kollega, sum beinanvegin foreslár praktiskar, gjørligar aktivitetar, sum eru tillagaðar til tína uppseting og avmarkingar.</p>

            <p><strong>Hugs hesa støðu:</strong> Tað er ein ólmur eftirmiddagur í barnagarðinum. Regn hevur avlýst útiveru, og tú hevur nú 12 ólm børn í aldrinum 3-5 ár í einum lítlum rúmi. Tú hevur vanlig tilfar sum pappír, litpennur, leikakubbar og bøkur, men tørvar nakað nýtt fyri at halda øllum í gongd.</p>

            <hr />
            <p><strong>Gott dømi á uppskoti (avrita/líma hetta):</strong></p>

            <p>Eg eri barnagarðslærari í Føroyum. Okkara útivist varð avlýst vegna regn.</p>
            <ul>
              <li><p>Luttakarar: 12 børn í aldrinum 3-5 ár</p></li>
              <li><p>Umhvørvi: Lítið innandura rúm</p></li>
              <li><p>Tøk: Pappír, litpennur, leikakubbar, bøkur, plastikkuppar</p></li>
              <li><p>Mál: Halda børnini í gongd í komandi tíma, og halda róliga og jákvæða stemningu</p></li>
            </ul>

            <p>Vinarliga foreslá nakrar lágar-fyrireikingaraktivitetar, sum eru róligar og hóskandi fyri ymiskar dugleikir. Spyr meg fyrst, um onkað tørvar at verða gjørt greiðligt.</p>

            <p><strong>Framhald uppskot:</strong><br />
             Um uppskotini ikki eru heilt viðkomandi, vegleiðing AI greiðligt. Til dømis:</p>
            <ul>
              <li><p>"Foreslá aktivitetar við enn einfaldari leiðbeiningum."</p></li>
              <li><p>"Okkum dámaði sagnaseigingin - gev okkum tvey fleiri rólig fortelling-baserad aktivitetar."</p></li>
              <li><p>"Ger aktivitetarnar skjótari, umleið 15 minuttir hvørt."</p></li>
            </ul>

            <hr />
            <h2 id="ætlanagerð-hjálpari"><strong>Ætlanagerð hjálpari</strong></h2>
            <p>Sum barnagarðslærari skalt tú gera vikuskipanir, mánaðarætlanir og tema-baserar aktivitetar. AI kann hjálpa tær við at skapa struktureraðar, aldursskipaðar ætlanir, sum spara tær tíð og tryggja, at øll viktig øki verða tikin við.</p>

            <p><strong>Hugs hesa støðu:</strong> Tú skalt gera eina vikuskipan um temaið "Høstur" fyri tíni 4-5 ára børn. Tú vil hava aktivitetar, sum fevna um ymisk øki - skapandi arbeiði, rørslu, mál, og náttúrukanningin.</p>

            <p><strong>Gott dømi á uppskoti:</strong></p>

            <p>Eg treysti hjálp til at gera eina vikuskipan fyri barnagarð í Føroyum um temaið "Høstur".</p>
            <ul>
              <li><p>Aldursgrupp: 4-5 ár (15 børn)</p></li>
              <li><p>Vikuskipan: Mánadag til fríggjudag, hvør dagur 4 tímar</p></li>
              <li><p>Øki at fevna um: Skapandi arbeiði, rørslu, málbygdir, náttúrukanning, samleik</p></li>
              <li><p>Tøk: Vanlig barnagarðstilfar, hóskandi høsturtilfar (lev, kastaniar, o.s.v.)</p></li>
            </ul>

            <p>Ger eina struktureraða vikuskipan við:</p>
            <ul>
              <li><p>Dagligar aktivitetar (30-45 minuttir hvørt)</p></li>
              <li><p>Øki-baserar mál</p></li>
              <li><p>Einfald tilfarlisti fyri hvønn dag</p></li>
              <li><p>Hugskot til "plan B" um veður ella annað ikki virkar</p></li>
            </ul>

            <p>Svara á føroyskum. Ongar persónupplýsingar.</p>

            <hr />
            <h2 id="samskifti-hjálpari"><strong>Samskifti hjálpari</strong></h2>
            <p>Gott og greitt samskifti við foreldur og kollegar ger øllum degnum lættari. Men at skriva stuttar boð kann vera torskellt, serliga tá tú ert trætt ella tíðarskuld. Hesin AI hjálpari skapar skjótt lættlasnar boð fyri foreldrasamskifti, kollegauppdateringar og vikuligir samandráttir.</p>

            <h3 id="dømi-samskifti-við-foreldur"><strong>Dømi: Samskifti við foreldur</strong></h3>
            <p><strong>Støða:</strong> Tú skalt senda eitt stutt SMS til foreldurnar um komandi temaviku um "Ólavsøku" og hvat børnini skulu hava við.</p>

            <p><strong>Gott uppskot:</strong></p>

            <p>Skriv eitt stutt, vinligt SMS til foreldrar um komandi temaviku.</p>
            <ul>
              <li><p>Tema: "Ólavsøka og føroysk mentan"</p></li>
              <li><p>Vikuna: 25.-29. juli</p></li>
              <li><p>Hvat at taka við: Føroysk klæði (um møguligt), pakka súrepli, eyka vatn</p></li>
              <li><p>Serligt: Dagfinn koma fólkadansarar</p></li>
              <li><p>Avmarkingur: Máx 160 tekn fyri SMS</p></li>
            </ul>

            <p>Skriv tað bæði sum stutt SMS og eitt eitt sindur longri boð fyri foreldragrupp. Svara á føroyskum. Ongar persónupplýsingar - brúka "Barn A/B" um neyðugt.</p>

            <hr />
            <h2 id="skjót-uppskot-realistisku-dømi"><strong>Skjót uppskot: Realistisku dømi</strong></h2>
            <p>Her eru nakrar dømi á støður, sum tú sum barnagarðslærari kannt møta. Hvørt dømi vísir, hvussu at geva AI nákvæman samanhang hjálpir at fáa <strong>betri, meira tillagaðar svar</strong>.</p>

            <h3 id="1-rólig-aktivitetar-fyri-lutarleika"><strong>1) Rólig aktivitetar fyri hvíldartíð</strong></h3>
            <p><strong>Støða:</strong> Eftir lunch tørva børnini eitt sindur róliga tíð, men sum ikki eru trætt nóg til at sova. Tú hevur eitt lítið rúm og will ongar larmandi aktivitetar.</p>

            <p><strong>Uppskot:</strong></p>
            <p>Eg treysti hjálp til róligar aktivitetar eftir lunch í barnagarðinum í Tórshavn (14:00-14:30). 10 børn (3-5 ár) tørva hvíld, men sum ikki sova. Rúmið er lítið og vit skulu vera lættir.</p>

            <p>Tøk: Bløtar teppi, smáar bøkur, pappír, mjúkir litpennur. Foreslá 4 róligar aktivitetar við:</p>
            <ul>
              <li><p>Uppsetingatíð ≤ 2 minuttir</p></li>
              <li><p>3 einføld stig</p></li>
              <li><p>Hvíslandi leiðbeiningar</p></li>
              <li><p>Skjót reingerð</p></li>
            </ul>

            <p>Svara á føroyskum. Ongar persónupplýsingar.</p>

            <h3 id="2-slemt-veður-backup-idéar"><strong>2) Slemm veður backup idear</strong></h3>
            <p><strong>Støða:</strong> Eitt óvart slemt veðurlag hevur broytt tínar útivistrarplaner, og tú tarvast skjótar indoor aktivitetar.</p>

            <p><strong>Uppskot:</strong></p>
            <p>Óvart regnveður í Klaksvík. Okkara garðsleikur varð avlýstur og nú hava vit 45 minuttir inni við 14 børnum (4-5 ár). Rúmið er miðal størð við vanlig tilfar.</p>

            <p>Treysti 5 engra-tilfar aktivitetar sum:</p>
            <ul>
              <li><p>Rørslubundin, men ikki ov larmandi</p></li>
              <li><p>5 einfald stig</p></li>
              <li><p>Kann skipast í 3 bólkar um neyðugt</p></li>
              <li><p>1-2 minuttar fyribúgving</p></li>
            </ul>

            <p>Svara á føroyskum. Ongar persónupplýsingar.</p>

            <h3 id="3-foreldrasamskifti-vikulig-uppdate"><strong>3) Foreldrasamskifti - vikulig update</strong></h3>
            <p><strong>Støða:</strong> Tú skalt senda ein stuttan samandrátt um vikuna til foreledrar, men vil ikki at tað skal verða ov formligt ella ov langt.</p>

            <p><strong>Uppskot:</strong></p>
            <p>Skriv ein stuttan, viniligan vikuligan samandrátt til foreldrar í barnagarðinum í Runavík. Vikuna: 4.-8. november.</p>

            <p>Innihald at fevna um:</p>
            <ul>
              <li><p>Tema: "Djór og teirra heimur"</p></li>
              <li><p>Høvuðsaktivitetar: Søgulesning, dýramyndir, túrsfarir</p></li>
              <li><p>Næsta viku: "Vetur og jól" byrjar</p></li>
              <li><p>Hugskot: Børnini kunnu taka leikadýr við</p></li>
            </ul>

            <p>Gør tað bæði sum:</p>
            <ul>
              <li><p>SMS (maks 160 tekn)</p></li>
              <li><p>Email (maks 300 orð)</p></li>
            </ul>

            <p>Svara á føroyskum. Ongar persónupplýsingar.</p>

            <hr />
            <h2 id="niðurstøða"><strong>Niðurstøða</strong></h2>
            <p>AI kann verða eitt virkiliga nýtiligt amboð fyri barnagarðslærarar, men tað er týdningarmikið at brúka tað á einum tryggum og viðkomandi hátti. Við at fylgja hesum vegleiðingum kanst tú:</p>

            <ul>
              <li><p>Spara tíð á ætlanagerð og aktivitetarskapjan</p></li>
              <li><p>Fáa frískar hugskot til daglígar arbeiðsuppgávur</p></li>
              <li><p>Bøta samskifti við foreldur og kollegar</p></li>
              <li><p>Halda altíð børnatrygd og persónvernd í fyrisetur</p></li>
            </ul>

            <p>Minnast: AI er eitt hjálparamboð, ikki eitt víkjandi amboð. Tín fagligi dømikraft og kærleiksfull umsorg eru og verða altíð kjarna í góðum barnagarðsarbeiði.</p>

            <hr />
            <div className="border-t pt-8 mt-12 text-center text-gray-600">
              <p>Takk fyri at lesa AI til barnagarð vegleiðingina!</p>
              <p className="mt-2">Fyri fleiri vegleiðingar og tilfar, vitja okkara dokumentatiónsmiðstøð.</p>
            </div>
          </article>
        </Section>
      </main>

      {!isPrintMode && <Footer />}
    </>
  );
}
